### ISSUE TITLE
Interaction between Month Calendar and List Calendar

### ISSUE THREAD

**Issue by Abdullah-Nasim** [memfis19/Cadar#5] opened 2016-12-08 06:08 UTC
I have noticed that when I click on some day like 18th of Dec 2016 on the month calendar the list calendar shows me the week starting from 19 Dec and the 18th get hidden on top. So the month calendar and the list calendar should be synchronized perfectly. How can I do that ?

**Comment by Abdullah-Nasim** [comment] 2016-12-08 07:21
Essentially the difference is of one week between month calendar and list calendar. When I click on 19th Dec in month calendar it shows me the correct week in list calendar but when I click on 20th Dec it scrolls to 26th of Dec in List Calendar which is wrong, it should stay to the week range 19 - 26 of Dec.

**Comment by memfis19** [comment] 2016-12-08 08:49
Hi, I'll take a look and fix it asap.

**Comment by memfis19** [comment] 2016-12-08 11:33
Sorry, I can't reproduce this issue. Can you send me your piece of code when you interact between calendars?

**Comment by Abdullah-Nasim** [comment] 2016-12-08 11:46
monthCalendar.setOnDayChangeListener(new OnDayChangeListener() {
            @Override
            public void onDayChanged(Calendar calendar) {

                listCalendar.setSelectedDay(DateUtils.setTimeToMidnight((Calendar) calendar.clone()), false);
            }
        });
        monthCalendar.setOnMonthChangeListener(new OnMonthChangeListener() {
            @Override
            public void onMonthChanged(Calendar calendar) {

                listCalendar.setSelectedDay(DateUtils.setTimeToMonthStart((Calendar) calendar.clone()), false);            }
        });

**Comment by Abdullah-Nasim** [comment] 2016-12-08 11:49
The code is same as your sample app.

**Comment by Abdullah-Nasim** [comment] 2016-12-08 11:58
The problem in in scroll position of the recyclerview please find below the attached example. 
![screenshot_20161208-155452](https://cloud.githubusercontent.com/assets/24429141/21009209/decdace8-bd5e-11e6-9f8e-5e8f4e3fd5db.png)

So I have clicked on 12th of April but the starting day in listCalendar is 16th of April which is wrong. The scroll position should be one step up.

**Comment by memfis19** [comment] 2016-12-08 12:09
Thanks. I got it. :)

**Comment by memfis19** [comment] 2016-12-08 13:08
Fixed in ```0.2.0```.

**Closed as completed by memfis19** 2016-12-08 13:08 UTC
